### ISSUE TITLE
大佬有遇到过睡眠唤醒后网速变慢的问题吗？

### ISSUE THREAD

**Issue by wancaibida** [paranoid2006/ASRock-Deskmini-H470-Hackintosh#2]
用的也是BCM94360CS2，长时间睡眠唤醒后会遇到网速变慢的问题，ping路由器延时有较大的波动，还一定概率的丢包，重启后又恢复正常。

电源管理那里的勾都去掉了：

<img width="588" alt="Screen Shot 2021-07-12 at 11 06 18" src="https://user-images.githubusercontent.com/5710237/125225066-7830f680-e283-11eb-84d2-ca27189627c2.png">

方便的话能大佬能提供一下你的BCM94360CS2购买链接吗？

**Comment by paranoid2006** [comment]
我用的02CS，3天线版本。小黄鱼上有。偶现过一次睡眠唤醒crash，自动重启了，之后睡眠正常。网速没关注，好像没有问题
